version: '3'

services:
  social_networlk_web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/social_network
    ports:
      - "9002:8000"
    container_name: social_netwrok_web_container
    command: "python manage.py runserver 0.0.0.0:8000"
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
    name: social-network
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16