# Generated by Django 4.2.7 on 2024-04-16 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netwrok', '0002_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', through='netwrok.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
